name: Dev CD
env:
  # TODO: Configure the following environment variables
  EB_PACKAGE_S3_BUCKET_NAME : "docker-test-app-s3-deployments"
  EB_APPLICATION_NAME       : "docker-test-app"
  EB_ENVIRONMENT_NAME       : "docker-test-app-env"
  DEPLOY_PACKAGE_NAME       : "docker-test-app-deployment-${{ github.sha }}.zip"
  AWS_REGION_NAME           : "ap-south-1"
  ECR_REPOSITORY            : "docker-test-app"

on: 
  push:
    branches: 
      - ecr-image-deployment

jobs:

  push_to_ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOYMENTUSER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEPLOYMENTUSER_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        working-directory: .
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and push it to ECR
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
